language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
script:
  - "bundle exec rake lint"
  - "bundle exec rake spec"
env:
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.4.3
  - PUPPET_VERSION=3.5.1
  - PUPPET_VERSION=3.6.2
  - PUPPET_VERSION=3.7.3
matrix:
  allow_failures:
    - env: PUPPET_VERSION=3.0.2
      rvm: 1.9.3
    - env: PUPPET_VERSION=3.1.1
      rvm: 1.9.3
    - env: PUPPET_VERSION=3.2.4
      rvm: 1.9.3
    - env: PUPPET_VERSION=3.3.2
      rvm: 1.9.3
    - env: PUPPET_VERSION=3.0.2
      rvm: 2.0.0
    - env: PUPPET_VERSION=3.1.1
      rvm: 2.0.0
    - env: PUPPET_VERSION=3.2.4
      rvm: 2.0.0
    - env: PUPPET_VERSION=3.3.2
      rvm: 2.0.0
    - env: PUPPET_VERSION=3.0.2
      rvm: 2.1.0
    - env: PUPPET_VERSION=3.1.1
      rvm: 2.1.0
    - env: PUPPET_VERSION=3.2.4
      rvm: 2.1.0
    - env: PUPPET_VERSION=3.3.2
      rvm: 2.1.0
